name: Example Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Pull Request Information
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
